server:
  servlet:
    context-path: /data
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spring-data2
    username: postgres
    password: Pfrjcvjltcfyn1992

pageSize: 5